# Generated by Django 5.0.3 on 2024-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_category_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos', verbose_name='Изображение'),
        ),
    ]
