# Generated by Django 5.0.3 on 2024-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(verbose_name='Время приготовления'),
        ),
    ]
