# Generated by Django 5.0.3 on 2024-04-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Описание', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Шаги приготовления', max_length=1000, verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(default='00:05:00', verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Название', max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
