# Generated by Django 5.0.3 on 2024-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_categories_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='Шаги приготовления', max_length=10000, verbose_name='Шаги приготовления'),
        ),
    ]
