# Generated by Django 5.0.3 on 2024-04-05 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor.fields.RichTextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=ckeditor.fields.RichTextField(default='Шаги приготовления', verbose_name='Шаги приготовления'),
        ),
    ]
